[var]
python_version = "3.11.0"

[task.pip-compile]
command = "pip-compile"
kit = "dev"
input = "requirements.in"
output = "requirements.txt"

[task.black]
command = "black ."
kit = "dev"
input = "^pip-compile"

[kit.main.packages]
python = "3.11.0"

[kit.dev.packages]
black = "23.1.0"
pip-tools = "6.12.2"
