[var]
python_version = "3.11.0"

[op.pip-compile]
command = "pip-compile"
kit = "dev"
input = "pyproject.toml"
output = "requirements.txt"

[op.black]
command = "black ."
kit = "dev"
input = ["^pip-compile", "footing/**"]

[kit.base]
packages = [
    "python==3.11.0",
]

[kit.dev]
packages = [
    "^base",
    "black==23.1.0",
    "pip-tools==6.12.2",
]
