project:
  name: footing

toolkits:
  - name: _base
    tools:
      - python==3.11
      - poetry==1.3.1
    manager: conda

  - name: default
    base: _base
    manager: pip
    file: pyproject.toml
